import { type AppType } from "next/app";
import { type Session } from "next-auth";
import Head from "next/head";
import { useRouter } from "next/router";
import { SessionProvider } from "next-auth/react";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import Link from "next/link";
import ArrowLeftIcon from "~/components/icons/ArrowLeft";

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  const { asPath } = useRouter();

  return (
    <SessionProvider session={session}>
      <Head>
        <title>Smart Cities</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <meta name="theme-color" content="#16a34a" />
        <link rel="manifest" href="/manifest.json" />
      </Head>
      <header className="fixed top-0 flex h-12 w-screen items-center bg-green-600 px-2 text-xl capitalize text-green-950">
        {asPath === "/" || asPath === "/home" ? (
          <h1>Home</h1>
        ) : (
          <Link href={"/"}>
            <h1 className="inline-flex items-center gap-1">
              <ArrowLeftIcon />
              {asPath.slice(1)}
            </h1>
          </Link>
        )}
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <Component {...pageProps} />
      </main>
      <footer className="fixed bottom-0 flex h-12 w-screen items-center justify-center bg-green-600 text-lg text-green-950">
        <nav>
          <ul className="flex gap-2">
            <li
              aria-current={
                asPath === "/" || asPath === "/home" ? "page" : "false"
              }
              className="rounded-xl px-3 py-1  aria-[current=page]:bg-green-800 aria-[current=page]:text-green-100 aria-[current=page]:shadow-md"
            >
              <Link href="/home">Home</Link>
            </li>
            <li
              aria-current={asPath === "/settings" ? "page" : "false"}
              className="rounded-xl px-3 py-1  aria-[current=page]:bg-green-800 aria-[current=page]:text-green-100 aria-[current=page]:shadow-md"
            >
              <Link href="/settings">Settings</Link>
            </li>
          </ul>
        </nav>
      </footer>
    </SessionProvider>
  );
};

export default api.withTRPC(MyApp);
